sudo: required
services:
  - docker

before_install:
  - docker build -t razorskiss/docker-react -f Dockerfile.dev .

script:
  - docker run razorskiss/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react1"
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-us-east-2-593504320416"
  bucket_path: "docker-react1"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"